# Generated by Django 3.2.3 on 2021-06-05 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cbv_firstapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentlist',
            old_name='student_no',
            new_name='student_id',
        ),
    ]
